version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btl_swift_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - btl_network

networks:
  btl_network:
    driver: bridge